connections {
    # Nome identificativo della connessione VPN Site-to-Site
    site1-site2 {
        # Indirizzo IP pubblico locale (CE1) da cui parte la VPN
        local_addrs = 203.0.113.2
        
        # Indirizzo IP pubblico remoto (CE2) a cui collegarsi
        remote_addrs = 203.0.113.6

        # Configurazione dell'autenticazione per il nodo locale
        local {
            auth = psk    # Tipo di autenticazione: Pre-Shared Key (chiave segreta condivisa)
            id = site1    # Identificativo univoco (ID) del nodo locale per la negoziazione
        }

        # Configurazione dell'autenticazione per il nodo remoto
        remote {
            auth = psk    # Richiede l'autenticazione tramite Pre-Shared Key anche dal nodo remoto
            id = site2    # Identificativo univoco (ID) atteso dal router remoto
        }

        # Blocco che definisce i parametri di cifratura per il traffico dati effettivo (Child SA)
        children {
            # Nome dell'associazione di sicurezza figlia (corrisponde al valore chiamato nello script con --child net-net)
            net-net {
                local_ts = 10.10.1.0/24     # Traffic Selector Locale: la rete LAN del Site 1
                remote_ts = 172.16.20.0/24  # Traffic Selector Remoto: la rete LAN del Site 2
                
                # Intervallo di tempo (in secondi) dopo il quale la chiave di cifratura dati viene rinnovata (5400s = 90 minuti)
                rekey_time = 5400
                
                # Proposta di cifratura per il protocollo ESP (traffico dati):
                # AES-GCM a 128 bit per cifratura/integrità e scambio chiavi su curva ellittica Curve25519 (x25519)
                esp_proposals = aes128gcm128-x25519
                start_action = start
            }
        }

        # Versione del protocollo di negoziazione IKE (IKEv2)
        version = 2
        
        # Proposta per la negoziazione del canale di controllo (IKE SA):
        # Cifratura AES-128, algoritmo di integrità/hashing SHA-256 e scambio chiavi Diffie-Hellman tramite Curve25519
        proposals = aes128-sha256-x25519
    }
}

# Sezione contenente le credenziali d'accesso e le chiavi segrete
secrets {
    # Blocco per la chiave segreta IKE associata a questo specifico tunnel
    ike-1 {
        id-1 = site1    # Corrisponde all'ID del nodo locale
        id-2 = site2    # Corrisponde all'ID del nodo remoto
        
        # La chiave Pre-Shared (PSK) scritta in formato esadecimale (prefisso 0x) 
        # Condivisa identica tra Site 1 e Site 2 per consentire l'autenticazione
        secret = 0x536F6E6F556E6150617373776F726453696375726131313F3F2121
    }
}
