connections {
    site2-site1 {
        # Indirizzo IP locale di CE2
        local_addrs = 203.0.113.6
        
        # Indirizzo IP remoto di CE1
        remote_addrs = 203.0.113.2

        # Configurazione dell'autenticazione per il nodo locale
        local {
            auth = psk    # Autenticazione tramite Pre-Shared Key
            id = site2    # Identificativo locale
        }

        # Configurazione dell'autenticazione attesa dal nodo remoto
        remote {
            auth = psk    # Richiede Pre-Shared Key dal remoto
            id = site1    # Identificativo remoto atteso
        }

        # Definizione del tunnel dati protetto
        children {
            net-net {
                local_ts = 172.16.20.0/24   # Traffic Selector Locale: la LAN2 protetta da MACsec
                remote_ts = 10.10.1.0/24    # Traffic Selector Remoto: la LAN1 del Site 1
                
                # Rinnovo della chiave di cifratura dati ogni 60 minuti
                rekey_time = 3600
                
                # Cifratura per il traffico dati
                esp_proposals = aes128gcm128-x25519
                start_action = none
            }
        }

        # Versione IKEv2 per la negoziazione
        version = 2
        
        # Proposta per la negoziazione del canale di controllo IKE SA
        proposals = aes128-sha256-x25519
    }
}

# Sezione per la memorizzazione delle credenziali di accesso
secrets {
    # Chiave IKE condivisa tra i due gateway
    ike-1 {
        id-1 = site2    # ID locale
        id-2 = site1    # ID remoto
        
        secret = 0x536F6E6F556E6150617373776F726453696375726131313F3F2121
    }
}
