connections {
    # Nome identificativo della connessione VPN Site-to-Site dal punto di vista del Site 2
    site2-site1 {
        # Indirizzo IP pubblico locale di CE2
        local_addrs = 203.0.113.6
        
        # Indirizzo IP pubblico remoto di CE1
        remote_addrs = 203.0.113.2

        # Configurazione dell'autenticazione per il nodo locale (Site 2)
        local {
            auth = psk    # Autenticazione tramite Pre-Shared Key
            id = site2    # Identificativo locale
        }

        # Configurazione dell'autenticazione attesa dal nodo remoto (Site 1)
        remote {
            auth = psk    # Richiede Pre-Shared Key dal remoto
            id = site1    # Identificativo remoto atteso
        }

        # Definizione del tunnel dati protetto (Child SA)
        children {
            net-net {
                local_ts = 172.16.20.0/24   # Traffic Selector Locale: la LAN2 protetta da MACsec
                remote_ts = 10.10.1.0/24    # Traffic Selector Remoto: la LAN1 del Site 1
                
                # Rinnovo della chiave di cifratura dati ogni 90 minuti (5400 secondi)
                rekey_time = 5400
                
                # Cifratura ESP per il traffico dati: AES-GCM a 128 bit e scambi Diffie-Hellman su Curve25519
                esp_proposals = aes128gcm128-x25519
                start_action = none
            }
        }

        # Versione IKEv2 per la negoziazione
        version = 2
        
        # Proposta per la negoziazione del canale di controllo IKE SA (AES-128, SHA-256, Curve25519)
        proposals = aes128-sha256-x25519
    }
}

# Sezione per la memorizzazione delle credenziali di accesso
secrets {
    # Chiave IKE condivisa tra i due gateway
    ike-1 {
        id-1 = site2    # ID locale
        id-2 = site1    # ID remoto
        
        # Stessa chiave Pre-Shared esadecimale configurata su CE1 per consentire l'accoppiamento
        secret = 0x536F6E6F556E6150617373776F726453696375726131313F3F2121
    }
}
