connections {
    lan1-lan3 {
        # L'indirizzo IP pubblico di questo firewall (eFW)
        local_addrs = 198.51.100.67
        # L'indirizzo IP pubblico del router remoto (R202)
        remote_addrs = 198.51.100.2
        
        # Parametri di autenticazione per il firewall locale
        local {
            auth = psk        # Usa l'autenticazione tramite Pre-Shared Key
            id = efw          # Si presenta al router remoto con l'identificativo "efw"
        }
        
        # Parametri di autenticazione attesi dal router remoto
        remote {
            auth = psk        # Si aspetta che anche l'altro router usi una password condivisa
            id = r202         # Si aspetta che il router remoto si identifichi come "r202"
        }
        
        # Fase 2 della VPN: definizione del tunnel per i dati reali
        children {
            av-tunnel {
                # Traffic Selectors
                # Il traffico in partenza dalla LAN1 locale (10.20.1.0/24)...
                local_ts = 10.20.1.0/24
                # ...e diretto alla LAN3 remota (10.30.1.0/24) deve essere infilato nel tunnel
                remote_ts = 10.30.1.0/24
                
                # Algoritmi di sicurezza usati per cifrare e proteggere i file scambiati
                esp_proposals = aes128gcm128-x25519
                start_action = start
            }
        }
        
        version = 2
        # Algoritmi di sicurezza per proteggere il canale di comunicazione iniziale 
        proposals = aes128-sha256-x25519
    }
}

# Sezione dedicata all'archiviazione delle password
secrets {
    ike-av {
        id-1 = efw    # Associa la password all'identificativo del firewall locale
        id-2 = r202   # Associa la password all'identificativo del router remoto
        
        secret = 0x43656e7472616c4e6f6465415654756e6e656c53656372657439392121
    }
}
