connections {
    lan3-lan1 {
        # Indirizzo IP locale (R202) da cui parte la VPN
        local_addrs = 198.51.100.2
        
        # Indirizzo IP remoto del concentratore VPN a cui collegarsi
        remote_addrs = 198.51.100.67

        # Configurazione dell'autenticazione locale
        local {
            auth = psk    # Autenticazione tramite Pre-Shared Key (chiave condivisa)
            id = r202     # Identificatore del nodo locale per la negoziazione
        }

        # Configurazione dell'autenticazione remota
        remote {
            auth = psk    # Richiede Pre-Shared Key anche dal nodo remoto
            id = efw      # ID atteso dal concentratore remoto
        }

        # Definisce le sottoreti i cui dati devono viaggiare protetti dentro il tunnel
        children {
            av-tunnel {
                local_ts = 10.30.1.0/24    # Traffic Selector Locale: la rete LAN3 di questo router
                remote_ts = 10.20.1.0/24   # Traffic Selector Remoto: la rete LAN1 dall'altra parte della VPN

                rekey_time = 5400
                
                # Algoritmi usati per cifrare il traffico dati reale (ESP):
                esp_proposals = aes128gcm128-x25519
                start_action = start
            }
        }

        version = 2
        
        # Algoritmi per il canale di controllo (IKE SA):
        proposals = aes128-sha256-x25519
    }
}

# Sezione contenente le credenziali segrete
secrets {
    # Blocco per la chiave segreta IKE associata al tunnel
    ike-av {
        id-1 = r202                                 
        id-2 = efw                                  
        secret = 0x43656e7472616c4e6f6465415654756e6e656c53656372657439392121    # La chiave condivisa tra i due gateway
    }
}
