connections {
    # Nome identificativo della connessione VPN Site-to-Site
    lan3-lan1 {
        # Indirizzo IP pubblico locale (R202) da cui parte la VPN
        local_addrs = 198.51.100.2
        
        # Indirizzo IP pubblico remoto del concentratore VPN a cui collegarsi
        remote_addrs = 198.51.100.67

        # Configurazione dell'autenticazione locale
        local {
            auth = psk    # Autenticazione tramite Pre-Shared Key (chiave condivisa)
            id = r202     # Identificatore (ID) del nodo locale per la negoziazione
        }

        # Configurazione dell'autenticazione remota
        remote {
            auth = psk    # Richiede Pre-Shared Key anche dal nodo remoto
            id = efw      # ID atteso dal concentratore remoto
        }

        # Definisce le sottoreti i cui dati devono viaggiare protetti dentro il tunnel (Child SA / IPsec)
        children {
            av-tunnel {
                local_ts = 10.30.1.0/24    # Traffic Selector Locale: la rete LAN3 di questo router
                remote_ts = 10.20.1.0/24   # Traffic Selector Remoto: la rete LAN1 dall'altra parte della VPN
                
                # Algoritmi usati per cifrare il traffico dati reale (ESP):
                # AES-GCM a 128 bit (cifratura + integrità) e Curve25519 per lo scambio chiavi (Diffie-Hellman)
                esp_proposals = aes128gcm128-x25519
                start_action = start
            }
        }

        # Versione del protocollo di negoziazione (IKEv2 è più sicuro e veloce di IKEv1)
        version = 2
        
        # Algoritmi per il canale di controllo (IKE SA):
        # Cifratura AES-128, Hashing SHA-256 e Curve25519 (x25519) per stabilire la sessione
        proposals = aes128-sha256-x25519
    }
}

# Sezione contenente le credenziali segrete
secrets {
    # Blocco per la chiave segreta IKE associata al tunnel
    ike-av {
        id-1 = r202                                 # Corrisponde all'ID locale
        id-2 = efw                                  # Corrisponde all'ID remoto
        secret = 0x43656e7472616c4e6f6465415654756e6e656c53656372657439392121    # La chiave Pre-Shared (PSK) condivisa tra i due gateway
    }
}
